[account]
uuid = "-"

[launch]
java_home = "_"
mode = "FireAndForget"

[snapshot.entries]
files = [
    "options.txt"
]
folders = [
    "config",
    "defaultconfigs"
]

[persist.entries]
files = [
    "options.txt"
]
folders = [
    "saves",
    "screenshots",
    "logs",
    "crash-reports"
]
