// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Summary { key: string, is_liked: boolean, name: string, author: string, summary: string, thumbnail: string | null, label: string | null, version: string, mod_loaders: Array<string>, }