//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polymerium.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polymerium.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Default.
        /// </summary>
        public static string AccountEntryButton_MarkAsDefaultMenu {
            get {
                return ResourceManager.GetString("AccountEntryButton_MarkAsDefaultMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string AccountEntryButton_RemoveMenu {
            get {
                return ResourceManager.GetString("AccountEntryButton_RemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AccountsView_AddAccountButtonText {
            get {
                return ResourceManager.GetString("AccountsView_AddAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsView_Title {
            get {
                return ResourceManager.GetString("AccountsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems something went wrong....
        /// </summary>
        public static string ExceptionView_Subtitle {
            get {
                return ResourceManager.GetString("ExceptionView_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died, but not dead....
        /// </summary>
        public static string ExceptionView_Title {
            get {
                return ResourceManager.GetString("ExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORT.
        /// </summary>
        public static string InstanceHomeView_AbortButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_AbortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchosen.
        /// </summary>
        public static string InstanceHomeView_AccountButtonSubtitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_AccountButtonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string InstanceHomeView_AccountButtonTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_AccountButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string InstanceHomeView_ActivitiesTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_ActivitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string InstanceHomeView_DashboardButtonSubtitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_DashboardButtonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string InstanceHomeView_DashboardButtonTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_DashboardButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject.
        /// </summary>
        public static string InstanceHomeView_DetachButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_DetachButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string InstanceHomeView_HourCountText {
            get {
                return ResourceManager.GetString("InstanceHomeView_HourCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KILL.
        /// </summary>
        public static string InstanceHomeView_KillButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_KillButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH.
        /// </summary>
        public static string InstanceHomeView_LaunchButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_LaunchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Pad.
        /// </summary>
        public static string InstanceHomeView_LaunchPadTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_LaunchPadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not set yet.
        /// </summary>
        public static string InstanceHomeView_NoAccountLabelText {
            get {
                return ResourceManager.GetString("InstanceHomeView_NoAccountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string InstanceHomeView_OverviewTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to packages.
        /// </summary>
        public static string InstanceHomeView_PackageCountText {
            get {
                return ResourceManager.GetString("InstanceHomeView_PackageCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready.
        /// </summary>
        public static string InstanceHomeView_ReadyLabelText {
            get {
                return ResourceManager.GetString("InstanceHomeView_ReadyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string InstanceHomeView_SeeMoreButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SeeMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string InstanceHomeView_SetupDetailsButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string InstanceHomeView_SetupTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string InstanceHomeView_SetupTypeText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string InstanceHomeView_SetupVersionText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string InstanceHomeView_WidgetsTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_WidgetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string MainWindow_AccountButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-b-b-bird, bird, bird, b-bird&apos;s the word....
        /// </summary>
        public static string MainWindow_BackgroundText {
            get {
                return ResourceManager.GetString("MainWindow_BackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_HomeButtonText {
            get {
                return ResourceManager.GetString("MainWindow_HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter entries by names....
        /// </summary>
        public static string MainWindow_InstanceFilterPlaceholder {
            get {
                return ResourceManager.GetString("MainWindow_InstanceFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Marketplace.
        /// </summary>
        public static string MainWindow_MarketplaceButtonText {
            get {
                return ResourceManager.GetString("MainWindow_MarketplaceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entries.
        /// </summary>
        public static string Shared_EmptyList {
            get {
                return ResourceManager.GetString("Shared_EmptyList", resourceCulture);
            }
        }
    }
}
