//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polymerium.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polymerium.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Default.
        /// </summary>
        public static string AccountEntryButton_MarkAsDefaultMenu {
            get {
                return ResourceManager.GetString("AccountEntryButton_MarkAsDefaultMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string AccountEntryButton_RemoveMenu {
            get {
                return ResourceManager.GetString("AccountEntryButton_RemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AccountsView_AddAccountButtonText {
            get {
                return ResourceManager.GetString("AccountsView_AddAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsView_Title {
            get {
                return ResourceManager.GetString("AccountsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems something went wrong....
        /// </summary>
        public static string ExceptionView_Subtitle {
            get {
                return ResourceManager.GetString("ExceptionView_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died, but not dead....
        /// </summary>
        public static string ExceptionView_Title {
            get {
                return ResourceManager.GetString("ExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORT.
        /// </summary>
        public static string InstanceHomeView_AbortButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_AbortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchosen.
        /// </summary>
        public static string InstanceHomeView_AccountButtonSubtitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_AccountButtonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string InstanceHomeView_AccountButtonTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_AccountButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string InstanceHomeView_ActivitiesTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_ActivitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string InstanceHomeView_DashboardButtonSubtitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_DashboardButtonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string InstanceHomeView_DashboardButtonTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_DashboardButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject.
        /// </summary>
        public static string InstanceHomeView_DetachButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_DetachButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string InstanceHomeView_HourCountText {
            get {
                return ResourceManager.GetString("InstanceHomeView_HourCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KILL.
        /// </summary>
        public static string InstanceHomeView_KillButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_KillButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH.
        /// </summary>
        public static string InstanceHomeView_LaunchButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_LaunchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Pad.
        /// </summary>
        public static string InstanceHomeView_LaunchPadTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_LaunchPadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not set yet.
        /// </summary>
        public static string InstanceHomeView_NoAccountLabelText {
            get {
                return ResourceManager.GetString("InstanceHomeView_NoAccountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string InstanceHomeView_OverviewTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to packages.
        /// </summary>
        public static string InstanceHomeView_PackageCountText {
            get {
                return ResourceManager.GetString("InstanceHomeView_PackageCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready.
        /// </summary>
        public static string InstanceHomeView_ReadyLabelText {
            get {
                return ResourceManager.GetString("InstanceHomeView_ReadyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string InstanceHomeView_SeeMoreButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SeeMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string InstanceHomeView_SetupDetailsButtonText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string InstanceHomeView_SetupTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string InstanceHomeView_SetupTypeText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string InstanceHomeView_SetupVersionText {
            get {
                return ResourceManager.GetString("InstanceHomeView_SetupVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string InstanceHomeView_WidgetsTitle {
            get {
                return ResourceManager.GetString("InstanceHomeView_WidgetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the application acts and chooses strategies.
        /// </summary>
        public static string InstancePropertiesView_BehaviorsSubtitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_BehaviorsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviors.
        /// </summary>
        public static string InstancePropertiesView_BehaviorsTitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_BehaviorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are applied instantly and can&apos;t be recovered.
        /// </summary>
        public static string InstancePropertiesView_DangerZoneSubtitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_DangerZoneSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger Zone.
        /// </summary>
        public static string InstancePropertiesView_DangerZoneTitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_DangerZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string InstancePropertiesView_DeleteButtonText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string InstancePropertiesView_DisplayNameLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_DisplayNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the asset and file validation process if the instance is already built and launch the game directly. May lead to crash if the assets are corrupted..
        /// </summary>
        public static string InstancePropertiesView_FastLaunchInfo {
            get {
                return ResourceManager.GetString("InstancePropertiesView_FastLaunchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Launch.
        /// </summary>
        public static string InstancePropertiesView_FastLaunchLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_FastLaunchLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance is busy now.
        /// </summary>
        public static string InstancePropertiesView_InoperableLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_InoperableLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Additional Arguments.
        /// </summary>
        public static string InstancePropertiesView_JavaAdditionalArgumentsLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_JavaAdditionalArgumentsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Home.
        /// </summary>
        public static string InstancePropertiesView_JavaLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_JavaLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Max Memory.
        /// </summary>
        public static string InstancePropertiesView_JavaMaxMemoryLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_JavaMaxMemoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        public static string InstancePropertiesView_JavaMaxMemoryUnitText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_JavaMaxMemoryUnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock by removing the attached pack brand/metadata that will make the instance losing the ability of updating but gaining the ability of editing all the imported packages..
        /// </summary>
        public static string InstancePropertiesView_LinkerInfo {
            get {
                return ResourceManager.GetString("InstancePropertiesView_LinkerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string InstancePropertiesView_LinkerLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_LinkerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries here will overwrite the global settings.
        /// </summary>
        public static string InstancePropertiesView_NavigateToGlobalButtonSubtitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_NavigateToGlobalButtonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the global settings page.
        /// </summary>
        public static string InstancePropertiesView_NavigateToGlobalButtonTitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_NavigateToGlobalButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration specified to the instance; left blank to refer to the global settings.
        /// </summary>
        public static string InstancePropertiesView_OverridesSubtitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_OverridesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Overrides.
        /// </summary>
        public static string InstancePropertiesView_OverridesTitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_OverridesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string InstancePropertiesView_RemoveButtonText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string InstancePropertiesView_RenameButtonText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_RenameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string InstancePropertiesView_ResetButtonText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This always leads to unexpected package conflicts due to poor management of package distribution sites. .
        /// </summary>
        public static string InstancePropertiesView_ResolvePackageDependenciesInfo {
            get {
                return ResourceManager.GetString("InstancePropertiesView_ResolvePackageDependenciesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Experimental] Resolve Package Dependencies.
        /// </summary>
        public static string InstancePropertiesView_ResolvePackageDependenciesLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_ResolvePackageDependenciesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrifice.
        /// </summary>
        public static string InstancePropertiesView_SacrificeLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_SacrificeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string InstancePropertiesView_SelectButtonText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_SelectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How this instance identify itself.
        /// </summary>
        public static string InstancePropertiesView_TitleSubtitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_TitleSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string InstancePropertiesView_TitleTitle {
            get {
                return ResourceManager.GetString("InstancePropertiesView_TitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string InstancePropertiesView_UnlockButtonText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_UnlockButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string InstancePropertiesView_WindowHeightLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_WindowHeightLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Initial Size.
        /// </summary>
        public static string InstancePropertiesView_WindowInitialSizeLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_WindowInitialSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string InstancePropertiesView_WindowWidthLabelText {
            get {
                return ResourceManager.GetString("InstancePropertiesView_WindowWidthLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating In Progress.
        /// </summary>
        public static string InstanceSetupView_InoperableLabelText {
            get {
                return ResourceManager.GetString("InstanceSetupView_InoperableLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Loader.
        /// </summary>
        public static string InstanceSetupView_LoaderLabelText {
            get {
                return ResourceManager.GetString("InstanceSetupView_LoaderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading packages information....
        /// </summary>
        public static string InstanceSetupView_LoadingPackageLabelText {
            get {
                return ResourceManager.GetString("InstanceSetupView_LoadingPackageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string InstanceSetupView_ReferenceUnavailableLabelText {
            get {
                return ResourceManager.GetString("InstanceSetupView_ReferenceUnavailableLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Version.
        /// </summary>
        public static string InstanceSetupView_SwitchVersionButtonText {
            get {
                return ResourceManager.GetString("InstanceSetupView_SwitchVersionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version.
        /// </summary>
        public static string InstanceSetupView_VersionLabelText {
            get {
                return ResourceManager.GetString("InstanceSetupView_VersionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string MainWindow_AccountButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-b-b-bird, bird, bird, b-bird&apos;s the word....
        /// </summary>
        public static string MainWindow_BackgroundText {
            get {
                return ResourceManager.GetString("MainWindow_BackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_HomeButtonText {
            get {
                return ResourceManager.GetString("MainWindow_HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter entries by names....
        /// </summary>
        public static string MainWindow_InstanceFilterPlaceholder {
            get {
                return ResourceManager.GetString("MainWindow_InstanceFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Marketplace.
        /// </summary>
        public static string MainWindow_MarketplaceButtonText {
            get {
                return ResourceManager.GetString("MainWindow_MarketplaceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entries.
        /// </summary>
        public static string Shared_EmptyListLabelText {
            get {
                return ResourceManager.GetString("Shared_EmptyListLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTERNAL LINK TO.
        /// </summary>
        public static string Shared_ExternalLinkLabelText {
            get {
                return ResourceManager.GetString("Shared_ExternalLinkLabelText", resourceCulture);
            }
        }
    }
}
